//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasmSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceGroup()
        {
            this.Devices = new HashSet<Device>();
            this.DeviceGroup1 = new HashSet<DeviceGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceGroup> DeviceGroup1 { get; set; }
        public virtual DeviceGroup DeviceGroup2 { get; set; }
    }
}
